print("welcome new player to GATES OF HELL")
playage=int(input("enter age"))
playgen=str(input("enter gender m for male f for female and n for non-binary")).lower()
playemail=str(input("plase may we have your email address for sending you the verification sorry but the only bots aloud are your enimies"))
usename=str(input("now whats you name adventurer"))
confirm=confirm=str(input("is this correct y or n only anything else is a instant yes"))
if confirm == "n":
  print("okay please type it again")
  playage=int(input("enter age"))
  playgen=str(input("enter gender m for male f for female and n for non-binary")).lower()
  playemail=str(input("plase may we have your email address for sending you the verification sorry but the only bots aloud are your enimies"))
  usename=str(input("now whats you name adventurer"))
  confirm=confirm=str(input("is this correct y or n only anything else is a instant yes"))
else:
  print("thank you sending verification now ")
  print("...")
  print("...")
  print("...")
  print("...")
  print("...")
  print("...")
  print("oppdies this is just a coding challange bye")
